import Image from "next/image";
import { Inter } from "next/font/google";
import HarryPage from "./harrypotter/harryPage";
import { Providers } from "@/store/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Harry Potter",
  description: "Generated by create next app",
};

export default function Home({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className={inter.className}>
        <Providers>
          <HarryPage />
        </Providers>
      </div>
    </>
  );
}
